name: ArkyneMinigameServer
version: 1.0.0
main: us.arkyne.server.MinigameMain
authors: [Chiller]
depend: [WorldEdit]
commands:
    arkyne:
        description: Admin use only
        permission: arkyne.manage
        usage: /arkyne <command>
        aliases: [ark]
permissions:
    arkyne.manage:
        description: Allows admins to manage the server