name: ArkyneServerPlugin
version: 1.0.0
main: us.arkyne.server.ArkyneMain
authors: [Chiller]
depend: [WorldEdit, Multiverse-Core]
load: POSTWORLD
commands:
    arkyne:
        description: Admin use only
        permission: arkyne.manage
        usage: /arkyne <subcommand>
        aliases: [ark]
    lobby:
        description: Lobby manage command
        permission: arkyne.manage
        usage: /lobby <subcommand>
permissions:
    arkyne.manage:
        description: Allows admins to manage the server